version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .docker_volumes/rabbitmq-data:/var/lib/rabbitmq
      - .docker_volumes/rabbitmq-logs:/var/log/rabbitmq
